version: '2'
services:
  mariadb:
    image: bitnami/mariadb:10.3
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  opencart:
    image: bitnami/opencart:3
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=qa_automation_opencart_1
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart_data:/bitnami'
    depends_on:
      - mariadb
  selenoid:
    image: aerokube/selenoid
    ports:
      - '4444:4444'
    volumes:
    - '$PWD/selenoid_conf:/etc/selenoid'
    - '/var/run/docker.sock:/var/run/docker.sock'
  selenoid-ui:
    image: aerokube/selenoid-ui
    links:
      - selenoid
    ports:
      - '8080:8080'
    command: ['--selenoid-uri', 'http://selenoid:4444']
  selenoid-firefox:
    image: selenoid/firefox
    depends_on:
      - selenoid
      - selenoid-ui
  selenoid-chrome:
    image: selenoid/chrome
    depends_on:
      - selenoid
      - selenoid-ui
  tests:
    build: ./
    image: opencart-tests
    volumes:
      - allure-results:/app/allure-results
    depends_on:
      - opencart
      - selenoid
      - selenoid-ui
      - selenoid-firefox
      - selenoid-chrome
  allure:
    image: frankescobar/allure-docker-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 'FALSE'
    ports:
      - '4040:4040'
    volumes:
      - allure-results:/app/allure-results
    depends_on:
      - tests
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  allure-results:
    driver: local